name: test
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: arrumando o python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: baixando o repo
      uses: actions/checkout@v4

    - name: instalando dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: pytest
